version: '3.9'

services:
  db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_DB: mynewdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: my_django
    environment:
      DATABASE_NAME: mynewdb
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DJANGO_SECRET_KEY: your-secret-key
      DJANGO_DEBUG: "False"
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
